version: '3.8'
services:

  redis:
    image: bitnami/redis:5.0
    networks:
      - hmpps
    container_name: inc-ui-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: inc-ui-auth
    ports:
      - '9090:8080'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/auth/health']
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0

  hmpps-prison-api:
    image: quay.io/hmpps/prison-api:latest
    networks:
      - hmpps
    container_name: inc-ui-prison
    depends_on:
      - hmpps-auth
    ports:
      - '8080:8080'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=nomis-hsqldb

  hmpps-incentives-api:
    image: quay.io/hmpps/hmpps-incentives-api:latest
    networks:
      - hmpps
    container_name: inc-ui-incentives
    depends_on:
      - hmpps-auth
    ports:
      - '8081:8080'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

  nomis-user-roles-api:
    image: quay.io/hmpps/nomis-user-roles-api:latest
    networks:
      - hmpps
    container_name: inc-ui-nomis-roles
    depends_on:
      - hmpps-auth
    ports:
      - '8082:8080'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - API_BASE_URL_OAUTH=http://hmpps-auth:8080/auth

  app:
    build: .
    networks:
      - hmpps
    container_name: inc-ui
    depends_on: [redis]
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=redis
      - HMPPS_AUTH_EXTERNAL_URL=http://localhost:9090/auth
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
      - HMPPS_PRISON_API_EXTERNAL_URL=http://localhost:8080
      - HMPPS_PRISON_API_URL=http://hmpps-prison-api:8080
      # These will need to match new creds in the seed auth service auth
      - API_CLIENT_ID=client-id
      - API_CLIENT_SECRET=client-secret
      - SYSTEM_CLIENT_ID=system-client-id
      - SYSTEM_CLIENT_SECRET=system-client-secret

networks:
  hmpps:
