version: '3.8'
services:

  redis:
    image: bitnami/redis:5.0
    networks:
      - hmpps
    container_name: inc-ui-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  minio:
    image: minio/minio
    networks:
      - hmpps
    container_name: inc-ui-minio
    environment:
      - MINIO_ROOT_USER=incentives
      - MINIO_ROOT_PASSWORD=incentives
    ports:
      - '9000:9000'
      - '9001:9001'
    command:
      - server
      - --address
      - :9000
      - --console-address
      - :9001
      - /data

  minio-init:
    image: minio/mc
    networks:
      - hmpps
    container_name: inc-ui-minio-init
    depends_on:
      - minio
    environment:
      - MINIO_ROOT_USER=incentives
      - MINIO_ROOT_PASSWORD=incentives
    volumes:
      - $PWD/server/testData/s3Bucket:/tmp/s3Bucket
    entrypoint: |
      /bin/sh -c "
        echo Provisioning bucket with minio
        until $$(curl --output /dev/null --silent http://minio:9000); do
          echo 'Waiting for http://minio:9000'
          sleep 3
        done
        mc config host add local http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD
        mc rb --force local/incentives
        mc mb local/incentives
        mc mirror /tmp/s3Bucket local/incentives
        exit 0
      "

networks:
  hmpps:
