# Runs the services needed for integation testing
# or the subset of services needed by the application if it is connected to `dev` HMPPS APIs

services:

  redis:
    image: redis:8
    networks:
      - hmpps
    container_name: inc-ui-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  minio:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
    networks:
      - hmpps
    container_name: inc-ui-minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 1s
      timeout: 3s
      retries: 15
    environment:
      - MINIO_ROOT_USER=incentives
      - MINIO_ROOT_PASSWORD=incentives
      - MINIO_SITE_REGION=eu-west-1
    ports:
      - '9000:9000'
      - '9001:9001'
    command:
      - server
      - --address
      - :9000
      - --console-address
      - :9001
      - /data

  minio-init:
    image: quay.io/minio/mc:RELEASE.2025-08-13T08-35-41Z
    networks:
      - hmpps
    container_name: inc-ui-minio-init
    depends_on:
      minio:
        condition: service_healthy
    environment:
      - MINIO_ROOT_USER=incentives
      - MINIO_ROOT_PASSWORD=incentives
      - MINIO_SITE_REGION=eu-west-1
    volumes:
      - $PWD/server/testData/s3Bucket:/tmp/s3Bucket
    entrypoint: |
      /bin/sh -c "
        echo Provisioning bucket with minio
        mc mb --region eu-west-1 --ignore-existing local/incentives
        mc mirror --overwrite /tmp/s3Bucket local/incentives
        exit 0
      "

  wiremock:
    image: wiremock/wiremock:3x
    networks:
      - hmpps
    container_name: inc-ui-wiremock
    restart: always
    ports:
      - '9091:8080'

networks:
  hmpps:
