# Runs the minimal set of services needed by the application if it is connected to `dev` HMPPS APIs
version: '3.8'
services:

  redis:
    image: bitnami/redis:5.0
    networks:
      - hmpps
    container_name: inc-ui-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  minio:
    image: minio/minio
    networks:
      - hmpps
    container_name: inc-ui-minio
    environment:
      - MINIO_ROOT_USER=incentives
      - MINIO_ROOT_PASSWORD=incentives
      - MINIO_SITE_REGION=eu-west-2
    ports:
      - '9000:9000'
      - '9001:9001'
    command:
      - server
      - --address
      - :9000
      - --console-address
      - :9001
      - /data

networks:
  hmpps:
