# Runs the services needed for integation testing
# or the subset of services needed by the application if it is connected to `dev` HMPPS APIs

services:

  redis:
    image: redis:8
    networks:
      - hmpps
    container_name: inc-ui-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  minio:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
    networks:
      - hmpps
    container_name: inc-ui-minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 1s
      timeout: 3s
      retries: 15
    environment:
      - MINIO_ROOT_USER=incentives
      - MINIO_ROOT_PASSWORD=incentives
      - MINIO_SITE_REGION=eu-west-1
    ports:
      - '9000:9000'
      - '9001:9001'
    command:
      - server
      - --address
      - :9000
      - --console-address
      - :9001
      - /data

  minio-init:
    image: public.ecr.aws/aws-cli/aws-cli:2.36.50
    networks:
      - hmpps
    container_name: inc-ui-minio-init
    depends_on:
      minio:
        condition: service_healthy
    environment:
      - AWS_ACCESS_KEY_ID=incentives
      - AWS_SECRET_ACCESS_KEY=incentives
      - AWS_DEFAULT_REGION=eu-west-1
    volumes:
      - $PWD/server/testData/s3Bucket:/tmp/s3Bucket:ro
    entrypoint: |
      /bin/sh -c "
        echo Provisioning S3 bucket...

        # Create S3 bucket
        aws --endpoint-url http://minio:9000 s3 mb s3://incentives

        # Copy test data
        aws --endpoint-url http://minio:9000 s3 sync /tmp/s3Bucket s3://incentives/
      "

  wiremock:
    image: wiremock/wiremock:3x
    networks:
      - hmpps
    container_name: inc-ui-wiremock
    restart: always
    ports:
      - '9091:8080'

networks:
  hmpps:
