version: '3.8'
services:

  redis:
    image: bitnami/redis:5.0
    networks:
      - hmpps_int
    container_name: inc-ui-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  wiremock:
    image: rodolpheche/wiremock
    networks:
    - hmpps_int
    container_name: inc-ui-wiremock
    restart: always
    ports:
      - '9091:8080'

networks:
  hmpps_int:
