---
generic-service:
  nameOverride: hmpps-incentives-ui

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-incentives-ui
    tag: app_version    # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: hmpps-incentives-ui-cert
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "120"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "120"

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  custommetrics:
    enabled: true
    scrapeInterval: 15s
    metricsPath: /metrics
    metricsPort: 3001

  # Environment variables to load into the deployment
  env:
    ENVIRONMENT: ""
    NODE_ENV: "production"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/"
    BUNYAN_NO_COLOR: "1"
    PHASE_NAME: ""
    FEATURE_ADD_TEST_ERROR_ENDPOINT: ""

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-incentives-ui:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      API_CLIENT_ID: "API_CLIENT_ID"
      API_CLIENT_SECRET: "API_CLIENT_SECRET"
      SYSTEM_CLIENT_ID: "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
      SESSION_SECRET: "SESSION_SECRET"
      ZENDESK_USERNAME: "ZENDESK_USERNAME"
      ZENDESK_TOKEN: "ZENDESK_TOKEN"
      GOOGLE_ANALYTICS_GA4_MEASUREMENT_ID: "GOOGLE_ANALYTICS_GA4_MEASUREMENT_ID"
      HOTJAR_SITE_ID: "HOTJAR_SITE_ID"
      SENTRY_DSN: "SENTRY_DSN"
    elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"
    analytical-platform-s3-bucket-output:
      S3_BUCKET_NAME: "bucket_name"

  allowlist:
    global-protect: "35.176.93.186/32"
    petty-france-wifi: "213.121.161.112/28"
    office: "217.33.148.210/32"
    quantum: "62.25.109.197/32"
    quantum_alt: "212.137.36.230/32"
    health-kick: "35.177.252.195/32"
    digitalprisons1: "52.56.112.98/32"
    digitalprisons2: "52.56.118.154/32"
    mojvpn: "81.134.202.29/32"
    j5-phones-1: "35.177.125.252/32"
    j5-phones-2: "35.177.137.160/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"
    dxc_webproxy1: "195.92.38.20/32"
    dxc_webproxy2: "195.92.38.21/32"
    dxc_webproxy3: "195.92.38.22/32"
    dxc_webprox23: "195.92.38.23/32"
    moj-official-tgw-prod: "51.149.250.0/24"
    moj-official-tgw-preprod: "51.149.251.0/24"
    moj-official-ark-c-expo-e: "51.149.249.0/29"
    moj-official-ark-c-vodafone: "194.33.248.0/29"
    moj-official-ark-f-vodafone: "194.33.249.0/29"
    moj-official-ark-f-expo-e: "51.149.249.32/29"
    sodexo-northumberland: "88.98.48.10/32"
    sodexo-northumberland2: "51.148.47.137/32"
    sodoxeo-forest-bank: "51.155.85.249/32"
    sodexo-peterborough: "51.155.55.241/32"
    serco: "217.22.14.0/24"
    ark-nps-hmcts-ttp1: "195.59.75.0/24"
    ark-nps-hmcts-ttp2: "194.33.192.0/25"
    ark-nps-hmcts-ttp3: "194.33.193.0/25"
    ark-nps-hmcts-ttp4: "194.33.196.0/25"
    ark-nps-hmcts-ttp5: "194.33.197.0/25"
    oakwood-01: "217.161.76.184/29"
    oakwood-02: "217.161.76.192/29"
    oakwood-1: "217.161.76.187/32"
    oakwood-2: "217.161.76.195/32"
    oakwood-3: "217.161.76.186/32"
    oakwood-4: "217.161.76.194/32"
    durham-tees-valley: "51.179.197.1/32"
    interservfls: "51.179.196.131/32"
    sodexo1: "80.86.46.16/32"
    sodexo2: "80.86.46.17/32"
    sodexo3: "80.86.46.18/32"
    sodexo4: "51.148.9.201"
    sscl-enhanced-external-subnet: "37.26.90.144/29"
    sscl-enhanced-additional-nat: "51.179.197.16/28"
    sscl-fb-standard-external-subnet: "185.40.10.8/29"
    sscl-cor-standard-external-subnet: "83.151.219.160/29"
    sscl-dr: "18.132.131.80"
    fivewells-1: "20.49.214.199/32"
    fivewells-2: "20.49.214.228/32"
    fivewells-3: "195.89.157.56/29"
    fivewells-4: "195.59.215.184/29"
    fivewells-5: "51.149.250.0/24"
    fivewells-6: "51.149.249.0/29"
    fivewells-7: "194.33.249.0/29"
    fivewells-8: "51.149.249.32/29"
    fivewells-9: "194.33.248.0/29"
    # hotjar servers: https://help.hotjar.com/hc/en-us/articles/115011789288
    hotjar-1: 18.203.61.76
    hotjar-2: 18.203.176.135
    hotjar-3: 52.17.197.221

generic-prometheus-alerts:
  targetApplication: hmpps-incentives-ui
  alertSeverity: digital-prison-service
