---
generic-service:
  nameOverride: hmpps-incentives-ui

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-incentives-ui
    tag: app_version    # override at deployment time
    port: 3000

  ingress:
    enabled: true
    contextColour: green
    host: app-hostname.local    # override per environment
    tlsSecretName: hmpps-incentives-ui-cert
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "120"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "120"

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-incentives-ui:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      API_CLIENT_ID: "API_CLIENT_ID"
      API_CLIENT_SECRET: "API_CLIENT_SECRET"
      SYSTEM_CLIENT_ID: "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
      SESSION_SECRET: "SESSION_SECRET"
      GOOGLE_ANALYTICS_ID: "GOOGLE_ANALYTICS_ID"
      FEEDBACK_URL: "FEEDBACK_URL"
    elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"

  allowlist:
    global-protect: "35.176.93.186/32"
    petty-france-wifi: "213.121.161.112/28"
    office: "217.33.148.210/32"
    quantum: "62.25.109.197/32"
    quantum_alt: "212.137.36.230/32"
    health-kick: "35.177.252.195/32"
    digitalprisons1: "52.56.112.98/32"
    digitalprisons2: "52.56.118.154/32"
    mojvpn: "81.134.202.29/32"
    j5-phones-1: "35.177.125.252/32"
    j5-phones-2: "35.177.137.160/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"
    dxc_webproxy1: "195.92.38.20/32"
    dxc_webproxy2: "195.92.38.21/32"
    dxc_webproxy3: "195.92.38.22/32"
    dxc_webprox23: "195.92.38.23/32"
    moj-official-tgw-prod: "51.149.250.0/24"
    moj-official-tgw-preprod: "51.149.251.0/24"
    moj-official-ark-c-expo-e: "51.149.249.0/29"
    moj-official-ark-c-vodafone: "194.33.248.0/29"
    moj-official-ark-f-vodafone: "194.33.249.0/29"
    moj-official-ark-f-expo-e: "51.149.249.32/29"

generic-prometheus-alerts:
  targetApplication: hmpps-incentives-ui
  alertSeverity: digital-prison-service
