---
generic-service:
  nameOverride: hmpps-incentives-ui
  productId: DPS020

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-incentives-ui
    tag: app_version    # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: hmpps-incentives-ui-cert
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "120"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "120"

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  env:
    ENVIRONMENT: ""
    NODE_ENV: "production"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"
    BUNYAN_NO_COLOR: "1"
    PHASE_NAME: ""
    FEATURE_ADD_TEST_ERROR_ENDPOINT: ""
    AUDIT_ENABLED: "false"
    AUDIT_SQS_REGION: "eu-west-2"
    AUDIT_SERVICE_NAME: "UNASSIGNED"

  namespace_secrets:
    hmpps-incentives-ui:
      FEEDBACK_URL: "FEEDBACK_URL"
      FEEDBACK_URL_ANALYTICS: "FEEDBACK_URL_ANALYTICS"
      FEEDBACK_URL_REVIEWS_TABLE: "FEEDBACK_URL_REVIEWS_TABLE"
      FEEDBACK_URL_TABLE: "FEEDBACK_URL_TABLE"
      GOOGLE_ANALYTICS_GA4_MEASUREMENT_ID: "GOOGLE_ANALYTICS_GA4_MEASUREMENT_ID"
      HOTJAR_SITE_ID: "HOTJAR_SITE_ID"
      ZENDESK_TOKEN: "ZENDESK_TOKEN"
      ZENDESK_USERNAME: "ZENDESK_USERNAME"
    hmpps-incentives-ui-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    hmpps-incentives-ui-auth-code:
      API_CLIENT_ID: "AUTH_CODE_CLIENT_ID"
      API_CLIENT_SECRET: "AUTH_CODE_CLIENT_SECRET"
    hmpps-incentives-ui-client-creds:
      SYSTEM_CLIENT_ID: "CLIENT_CREDS_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "CLIENT_CREDS_CLIENT_SECRET"
    hmpps-incentives-ui-session-secret:
      SESSION_SECRET: 'SESSION_SECRET'
    elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"
    analytical-platform-s3-bucket-output:
      S3_BUCKET_NAME: "bucket_name"
    # sqs-hmpps-audit-secret:
    #   AUDIT_SQS_QUEUE_URL: "sqs_queue_url"
    #   AUDIT_SQS_QUEUE_NAME: "sqs_queue_name"

  allowlist:
    groups:
      - digital_staff_and_mojo
      - moj_cloud_platform
      - prisons
      - private_prisons

  scheduledDowntime:
    # NOTE: API starts at 6.49am UTC, stops at 21:58pm UTC
    startup: '00 7 * * 1-5' # Start at 7.00am UTC Monday-Friday
    shutdown: '50 21 * * 1-5' # Stop at 9.50pm UTC Monday-Friday

generic-prometheus-alerts:
  targetApplication: hmpps-incentives-ui
