generic-service:
  nameOverride: hmpps-incentives-ui
  productId: DPS020

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-incentives-ui
    tag: app_version # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-incentives-ui-cert
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "120"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "120"

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  custommetrics:
    enabled: true
    scrapeInterval: 15s
    metricsPath: /metrics
    metricsPort: 3001

  # Environment variables to load into the deployment
  env:
    ENVIRONMENT: ""
    NODE_ENV: "production"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/"
    BUNYAN_NO_COLOR: "1"
    PHASE_NAME: ""
    FEATURE_ADD_TEST_ERROR_ENDPOINT: ""

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-incentives-ui:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      API_CLIENT_ID: "API_CLIENT_ID"
      API_CLIENT_SECRET: "API_CLIENT_SECRET"
      SYSTEM_CLIENT_ID: "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
      SESSION_SECRET: "SESSION_SECRET"
      ZENDESK_USERNAME: "ZENDESK_USERNAME"
      ZENDESK_TOKEN: "ZENDESK_TOKEN"
      GOOGLE_ANALYTICS_GA4_MEASUREMENT_ID: "GOOGLE_ANALYTICS_GA4_MEASUREMENT_ID"
      HOTJAR_SITE_ID: "HOTJAR_SITE_ID"
      SENTRY_DSN: "SENTRY_DSN"
    elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"
    analytical-platform-s3-bucket-output:
      S3_BUCKET_NAME: "bucket_name"

  allowlist:
    undefined: internal,prisons,private_prisons/32
    hotjar-1: 18.203.61.76/32
    hotjar-2: 18.203.176.135/32
    hotjar-3: 52.17.197.221/32
    groups: []

generic-prometheus-alerts:
  targetApplication: hmpps-incentives-ui
  alertSeverity: digital-prison-service
