---
# Per environment values which override defaults in hmpps-incentives-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: incentives-ui.hmpps.service.justice.gov.uk
    contextColour: green

  env:
    INGRESS_URL: "https://incentives-ui.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service
