---
generic-service:
  replicaCount: 2

  serviceAccountName: hmpps-incentives-dev-analytical-platform

  ingress:
    host: incentives-ui-dev.hmpps.service.justice.gov.uk

  allowlist: null

  env:
    ENVIRONMENT: dev
    S3_REGION: eu-west-2
    INGRESS_URL: "https://incentives-ui-dev.hmpps.service.justice.gov.uk"
    DPS_URL: "https://digital-dev.prison.service.justice.gov.uk"
    SUPPORT_URL: "https://support-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    HMPPS_INCENTIVES_API_URL: "https://incentives-api-dev.hmpps.service.justice.gov.uk"
    HMPPS_PRISON_API_URL: "https://prison-api-dev.prison.service.justice.gov.uk"
    NOMIS_USER_ROLES_API_URL: "https://nomis-user-roles-api-dev.prison.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components-dev.hmpps.service.justice.gov.uk"
    PHASE_NAME: "DEV"
    FEATURE_FS_CACHE: "true"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
