---
generic-service:
  replicaCount: 2

  scheduledDowntime:
    enabled: true

  serviceAccountName: hmpps-incentives-preprod-analytical-platform

  ingress:
    host: incentives-ui-preprod.hmpps.service.justice.gov.uk

  allowlist:
    groups:
      - internal
      - prisons
      - private_prisons

    # hotjar servers: https://help.hotjar.com/hc/en-us/articles/115011789288
    hotjar-1: 18.203.61.76
    hotjar-2: 18.203.176.135
    hotjar-3: 52.17.197.221

  env:
    ENVIRONMENT: preprod
    S3_REGION: eu-west-2
    INGRESS_URL: "https://incentives-ui-preprod.hmpps.service.justice.gov.uk"
    DPS_URL: "https://digital-preprod.prison.service.justice.gov.uk"
    SUPPORT_URL: "https://support-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    HMPPS_INCENTIVES_API_URL: "https://incentives-api-preprod.hmpps.service.justice.gov.uk"
    HMPPS_PRISON_API_URL: "https://api-preprod.prison.service.justice.gov.uk"
    NOMIS_USER_ROLES_API_URL: "https://nomis-user-pp.aks-live-1.studio-hosting.service.justice.gov.uk"
    MANAGE_USERS_API_URL: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components-preprod.hmpps.service.justice.gov.uk"
    PHASE_NAME: "PRE-PRODUCTION"
    FEATURE_FS_CACHE: "true"
    FEATURE_PRECACHE_TABLES: "true"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
