---
# Per environment values which override defaults in hmpps-incentives-ui/values.yaml

generic-service:
  serviceAccountName: hmpps-incentives-prod-analytical-platform

  ingress:
    host: incentives-ui.hmpps.service.justice.gov.uk

  env:
    ENVIRONMENT: prod
    INGRESS_URL: "https://incentives-ui.hmpps.service.justice.gov.uk"
    DPS_URL: "https://digital.prison.service.justice.gov.uk"
    SUPPORT_URL: "https://support.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    HMPPS_INCENTIVES_API_URL: "https://incentives-api.hmpps.service.justice.gov.uk"
    HMPPS_PRISON_API_URL: "https://api.prison.service.justice.gov.uk"
    NOMIS_USER_ROLES_API_URL: "https://nomis-user.aks-live-1.studio-hosting.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    ANALYTICS_DATA_STALE_AFTER_DAYS: "3"
    FEATURE_HIDE_DAYS_COLUMNS_IN_INCENTIVES_TABLE: "true"
    FEATURE_FS_CACHE: "true"
    FEATURE_PRECACHE_TABLES: "true"
    FEATURE_NEW_REVIEWS_TABLE: "AGI,AYI,BAI,BFI,BLI,BMI,BNI,BSI,BRI,CDI,CFI,CKI,CWI,DAI,DHI,DMI,DTI,DWI,EEI,ESI,EWI,EXI,FHI,FMI,FSI,FYI,GHI,GMI,GNI,HBI,HCI,HDI,HEI,HHI,HLI,HMI,HOI,HPI,HVI,KMI,KVI,LCI,LEI,LFI,LHI,LII,LNI,LTI,LYI,MDI,MHI,MTI,NHI,NSI,NWI,ONI,PDI,PNI,SDI,SFI,SHI,SNI,SPI,STC3,SWI,UKI,UPI,VEI,WCI,WDI,WEI,WHI,WII,WLI,WMI,WNI,WTI,WYI"

  resources:
    limits:
      memory: 2048Mi
