---
# Per environment values which override defaults in hmpps-incentives-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: incentives-ui-preprod.hmpps.service.justice.gov.uk
    contextColour: green

  env:
    INGRESS_URL: "https://incentives-ui-preprod.hmpps.service.justice.gov.uk"
    DPS_URL: "https://digital-preprod.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    HMPPS_PRISON_API_URL: "https://api-preprod.prison.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
