---
# Per environment values which override defaults in hmpps-incentives-ui/values.yaml

generic-service:
  serviceAccountName: hmpps-incentives-prod-analytical-platform

  ingress:
    host: incentives-ui.hmpps.service.justice.gov.uk

  env:
    ENVIRONMENT: prod
    INGRESS_URL: "https://incentives-ui.hmpps.service.justice.gov.uk"
    DPS_URL: "https://digital.prison.service.justice.gov.uk"
    SUPPORT_URL: "https://support.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    HMPPS_INCENTIVES_API_URL: "https://incentives-api.hmpps.service.justice.gov.uk"
    HMPPS_PRISON_API_URL: "https://api.prison.service.justice.gov.uk"
    NOMIS_USER_ROLES_API_URL: "https://nomis-user.aks-live-1.studio-hosting.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    ANALYTICS_DATA_STALE_AFTER_DAYS: "3"
    FEATURE_HIDE_DAYS_COLUMNS_IN_INCENTIVES_TABLE: "true"
    FEATURE_FS_CACHE: "true"
    FEATURE_PRECACHE_TABLES: "true"
    FEATURE_NEW_REVIEWS_TABLE: "BAI,BFI,BLI,BRI,CDI,CFI,CWI,DAI,EXI,GHI,GMI,HBI,HOI,HPI,HVI,KMI,LCI,LFI,LII,LTI,LYI,MHI,MTI,NSI,NWI,ONI,PDI,PNI,SWI,UKI,VEI,WCI,WDI,WHI,WII,WLI,WMI,WNI,WTI"

  resources:
    limits:
      memory: 2048Mi
