#!/bin/bash

# Check test data doesn't contain booking IDs
if grep -q book server/testData/s3Bucket/*/*; then
  echo "FAIL: Possibly booking IDs/sensitive information in test data"
  exit 1
# else
  # OK: Test data shouldn't contain booking IDs
fi

NODE_ENV=dev \
npm run precommit:secrets \
&& npm run precommit:lint \
&& npm run precommit:verify
